#!/usr/bin/env python3

#
# Ioreth - An APRS library and bot
# Copyright (C) 2020  Alexandre Erwin Ittner, PP5ITT <alexandre@ittner.com.br>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


import sys
import logging
import argparse

logging.basicConfig(
    level=logging.INFO, format="%(asctime)-15s %(levelname)s: %(name)s::%(funcName)s %(message)s"
)
logger = logging.getLogger('iorethd')

from ioreth.bot import ReplyBot


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
                    prog='iorethd',
                    description='Experimental APRS bot',
                    epilog='')
    parser.add_argument('-d', '--debug', action='store_true',
                        help='Set debug logging')
    parser.add_argument('-c', '--config', type=str, default='/etc/aprsbot.conf',
                        help='Use config file')

    args = parser.parse_args()

    if args.debug:
        logger.setLevel(logging.DEBUG)
        for l in logger.getChildren():
            l.setLevel(logging.DEBUG)
        logger.debug('Debug logging enabled')

    b = ReplyBot(args.config)
    b.connect()
    b.start()
